name: 'Build Corne NiceHat Firmware'
on:
  workflow_dispatch:  # can be triggered manually
  push:               # automatically run on changes to following paths
    paths:
      - 'build/corne_nicehat.yaml'
      - 'config/west.yml'
      - 'config/corne.*'
      - 'config/shared.dtsi'

jobs:
  build:
    # uses: zmkfirmware/zmk/.github/workflows/build-user-config.yml@main
    uses: petejohanson/zmk/.github/workflows/build-user-config.yml@core-dump-experimentation
    with:
      build_matrix_path: build/corne_nicehat.yaml
      archive_name: corne_nicehat
